version: '3.9'

services:
  postgres:
    # image - образ БД из докерхаба + настройки БД
    image: 'postgres:14'
    container_name: 'archivist-bd'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=SBRF_%1601'
      - 'POSTGRES_DB=archivist'
    ports:
      - '5432:5432'
    networks:
      - tg-bot

  app:
    build: ./
    container_name: archivist
    ports:
      - '8092:8092'
    networks:
      - tg-bot

networks:
  tg-bot:
    external: true
